# -*- coding: utf-8 -*-
"""cut-recording-length.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/102oNFbWu19l6X28riIGDBw1Rqv4CTczz
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import numpy as np
import shutil

data = "/content/drive/MyDrive/cs410/data" # path to data dir
files_to_split = os.path.join(data, "subject_21/session_0") # or whatever path to your two files

files = os.listdir(files_to_split)
files

eyes_closed = pd.read_csv(os.path.join(files_to_split, files[0]))
eyes_open = pd.read_csv(os.path.join(files_to_split, files[1]))

eyes_closed.shape

eyes_open.shape

# takes tuple of two dataframes (eyes_open, eyes_closed) and returns copies with the first 50 rows removed
def remove_first_50_rows(eyes_open, eyes_closed):
  eyes_open = eyes_open.drop([i for i in range(50)])
  eyes_closed = eyes_closed.drop([i for i in range(50)])

  return (eyes_open, eyes_closed)

# export recordings already around 45s in length, otherwise print size of CSVs
def export_short_recordings(eyes_open, eyes_closed, dest_path):

  if (eyes_open.shape[0] < 6000) & (eyes_closed.shape[0] < 6000):
    eyes_open.to_csv("eyes_open.csv")
    eyes_closed.to_csv("eyes_closed.csv")
    vm_root = "/content/drive"
    shutil.move(os.path.join(vm_root, "eyes_open.csv"), dest_path)
    shutil.move(os.path.join(vm_root, "eyes_closed.csv"), dest_path)
  else:
    print("shape of eyes_open.csv:")
    print(eyes_open.shape[0])
    print("shape of eyes_closed.csv:")
    print(eyes_closed.shape[0])

# returns a dataframe that can be evenly split into 2500-column dataframes, and the number of dataframes it can be split into
def trim_length(df):
  mod = df.shape[0] % 2500 # or length of smallest individual csv file AFTER trimming first 50 cols
  start = df.shape[0]-mod
  end = df.shape[0]
  df_trimmed = df.drop([i for i in range(start,end)])

  return (df_trimmed, df_trimmed.shape[0] // 2500)

def process_long_recording(eyes_open, eyes_closed, dest_path):
  # trim first 50 columns
  (eyes_open, eyes_closed) = remove_first_50_rows(*(eyes_open, eyes_closed))

  # helper for trimming dataframes
  eyes_open = trim_length(eyes_open)[0]
  splits_open = trim_length(eyes_open)[1]

  eyes_closed = trim_length(eyes_closed)[0]
  splits_closed = trim_length(eyes_closed)[1]

  splits = min(splits_open, splits_closed)

  # split into n small recordings
  for i in range(splits):
    eo = eyes_open.iloc[i*2500:(i+1)*2500]
    ec = eyes_closed.iloc[i*2500:(i+1)*2500]

    export_short_recordings(*(eo, ec), dest_path=dest_path)
    print(f"Exported recording set #{i} with shapes {eo.shape[0]}, {ec.shape[0]}")

  print(f"Successfully exported {splits} sets of 2500 rows to CSVs")

subjects = os.listdir(data)
long_videos = []

# get long recordings
for i in range (len(subjects)):
  sub_path = os.path.join(data, subjects[i])
  sessions = os.listdir(sub_path)

  for j in range(len(sessions)):
    session = os.path.join(sub_path, sessions[j])

    open = pd.read_csv(os.path.join(session, 'eyes_open.csv'))
    closed = pd.read_csv(os.path.join(session, 'eyes_closed.csv'))

    if (open.shape[0] > 6000) & (closed.shape[0] > 6000):
      print(f"need to process recordings from session {session}, subject {subjects[i]}")
      long_videos.append((open, closed, session))
      continue

    elif (open.shape[0] < 6000) & (closed.shape[0] < 6000):
      print(f"no need to process recording for session {session}, subject {subjects[i]}")
      continue

    elif (open.shape[0] > 6000 & closed.shape[0] < 6000) | (open.shape[0] < 6000 & closed.shape[0] > 6000):
      print(f"ERROR: lengths of eyes_open.csv and eyes_closed.csv for session {session}, subject {subjects[i]} vary greatly in length.")
      break

for i in range(len(long_videos)):
  long_videos[i] = process_long_recording(*long_videos[i][:1], dest_path=session)

mod = eyes_open.shape[0] % 3100 #remainder of dividing df length by per-split length (3100)
# can adjust the modulus to make more/less datasets (the smaller mod value, the better)
start = eyes_open.shape[0]-mod
end = eyes_open.shape[0]
eyes_open_trimmed = eyes_open.drop([i for i in range(start,end)])
eyes_open_trimmed.shape[0] % 3100

eo1, eo2, eo3, eo4, eo5, eo6, eo7, eo8, eo9, eo10 = np.split(eyes_open_trimmed, 10)

eo1.to_csv("eyes_open_1.csv")
eo2.to_csv("eyes_open_2.csv")
eo3.to_csv("eyes_open_3.csv")
eo4.to_csv("eyes_open_4.csv")
eo5.to_csv("eyes_open_5.csv")
eo6.to_csv("eyes_open_6.csv")
eo7.to_csv("eyes_open_7.csv")
eo8.to_csv("eyes_open_8.csv")
eo9.to_csv("eyes_open_9.csv")
eo10.to_csv("eyes_open_10.csv")

shutil.move("eyes_open_1.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_0")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_0")
shutil.move("eyes_open_2.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_1")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_1")
shutil.move("eyes_open_3.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_2")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_2")
shutil.move("eyes_open_4.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_3")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_3")
shutil.move("eyes_open_5.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_4")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_4")
shutil.move("eyes_open_6.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_5")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_5")
shutil.move("eyes_open_7.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_6")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_6")
shutil.move("eyes_open_8.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_7")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_7")
shutil.move("eyes_open_9.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_8")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_8")
shutil.move("eyes_open_10.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_9")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_9")

mod = eyes_closed.shape[0] % 3100
mod
start = eyes_closed.shape[0]-mod
end = eyes_closed.shape[0]
eyes_closed_trimmed = eyes_closed.drop([i for i in range(start,end)])
eyes_closed_trimmed.shape[0] % 3100

ec1, ec2, ec3, ec4, ec5, ec6, ec7, ec8, ec9, ec10 = np.split(eyes_closed_trimmed, 10)

ec1.to_csv("eyes_closed_1.csv")
ec2.to_csv("eyes_closed_2.csv")
ec3.to_csv("eyes_closed_3.csv")
ec4.to_csv("eyes_closed_4.csv")
ec5.to_csv("eyes_closed_5.csv")
ec6.to_csv("eyes_closed_6.csv")
ec7.to_csv("eyes_closed_7.csv")
ec8.to_csv("eyes_closed_8.csv")
ec9.to_csv("eyes_closed_9.csv")
ec10.to_csv("eyes_closed_10.csv")

shutil.move("eyes_closed_1.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_0")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_0")
shutil.move("eyes_closed_2.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_1")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_1")
shutil.move("eyes_closed_3.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_2")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_2")
shutil.move("eyes_closed_4.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_3")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_3")
shutil.move("eyes_closed_5.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_4")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_4")
shutil.move("eyes_closed_6.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_5")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_5")
shutil.move("eyes_closed_7.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_6")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_6")
shutil.move("eyes_closed_8.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_7")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_7")
shutil.move("eyes_closed_9.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_8")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_8")
shutil.move("eyes_closed_10.csv", "/content/drive/MyDrive/cs410/data/subject_8/session_9")
shutil.copy("/content/drive/MyDrive/cs410/data/subject_8/Metadata.csv",
            "/content/drive/MyDrive/cs410/data/subject_8/session_9")

# set time to start at 0 milliseconds - eyes open
time_offset = eyes_open['seconds_elapsed'].iloc[0]
time_norm = lambda x: x - time_offset
eyes_open['seconds_elapsed'] = eyes_open['seconds_elapsed'].apply(time_norm)

# set time to start at 0 milliseconds - eyes closed
time_offset = eyes_closed['seconds_elapsed'].iloc[0]
time_norm = lambda x: x - time_offset
eyes_closed['seconds_elapsed'] = eyes_closed['seconds_elapsed'].apply(time_norm)